version: '2.1'
services:
    local-ui:
        restart: "always"
        build: .
        labels:
            io.balena.features.supervisor-api: '1'
            io.balena.features.balena-api: '1'
        network_mode: "host"
        ports:
            - "48485:48485"