version: '2.1'
services:
    local-ui:
        restart: "always"
        build: .
        privileged: true
        network_mode: host
        labels:
            io.balena.features.supervisor-api: '1'
            io.balena.features.balena-api: '1'
            io.balena.features.dbus: '1'
        ports:
            - "80:80"
        environment:
            - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
